CREATE TABLE TABLE_TEMP(DATEINSERT DATETIME, COMMENTAIRE NVARCHAR(2000))

INSERT INTO	TABLE_TEMP VALUES(GETDATE(),'blabla')

SELECT * FROM TABLE_TEMP

TRUNCATE TABLE TABLE_TEMP

DROP TABLE TABLE_TEMP
