SELECT 	COM.COM_CODE, COM.COM_DESC Customer, ADR.ADR_TEXT Adresse
FROM 	R5COMPANIES COM, R5ADDRESS ADR
WHERE 	ADR.ADR_CODE=  COM.COM_CODE||'#'||COM_ORG
AND 	ADR.ADR_RTYPE = 'I'
AND 	COM.COM_CODE = #prompt('SEL_COM')# 
AND 	ROWNUM = 1